import {
  User,
  TeacherAsset,
  Extracurricular,
  StudentInterest,
  MentoringLog,
  Achievement,
  EvaluationFeedback,
  AchievementStats,
  FeedbackSummary,
} from '../src/types.js';

export class DataStore {
  users: User[] = [
    {
      id: 1,
      nama: 'Muhammad Salman Al farisi, S.Pd.',
      username: 'kasek',
      password_hash: 'password123',
      role: 'kepala_sekolah',
      nip_nisn: '196805121992031005',
      nomor_wa: '081234567890',
      jabatan: 'Kepala UPT SD Negeri 275 Gresik',
      email: 'salman.sdn275@gresik.sch.id',
    },
    {
      id: 2,
      nama: 'Nur Aini, S.Pd',
      username: 'guru_nuraini',
      password_hash: 'password123',
      role: 'guru',
      nip_nisn: '198503142010012021',
      nomor_wa: '081234567891',
      jabatan: 'Guru Kelas 5 / Pembina Robotika',
      email: 'nuraini.spd@gresik.sch.id',
    },
    {
      id: 3,
      nama: 'Joko Santoso, S.Pd',
      username: 'guru_joko',
      password_hash: 'password123',
      role: 'guru',
      nip_nisn: '198708212011011009',
      nomor_wa: '081234567892',
      jabatan: 'Guru PJOK / Pembina Catur & Atletik',
      email: 'joko.santoso@gresik.sch.id',
    },
    {
      id: 4,
      nama: 'Siti Rahayu, S.Pd',
      username: 'guru_siti',
      password_hash: 'password123',
      role: 'guru',
      nip_nisn: '199011052015022004',
      nomor_wa: '081234567893',
      jabatan: 'Guru Seni & Budaya / Pembina Seni Tari',
      email: 'siti.rahayu@gresik.sch.id',
    },
    {
      id: 5,
      nama: 'Ahmad Zaki, S.Pd.I',
      username: 'guru_zaki',
      password_hash: 'password123',
      role: 'guru',
      nip_nisn: '199304102019031008',
      nomor_wa: '081234567894',
      jabatan: 'Guru PAI / Pembina Tilawatil Qur\'an & Hadrah',
      email: 'ahmad.zaki@gresik.sch.id',
    },
    {
      id: 6,
      nama: 'Budi Pratama',
      username: 'murid_budi',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456789',
      kelas: 'Kelas 5A',
      jenis_kelamin: 'L',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2014-04-12',
      alamat: 'Jl. Raya Kartini No. 45, Kebomas, Gresik',
      nama_ortu: 'Bpk. Agus Pratama',
      wa_ortu: '085732112233',
      minat_utama: 'Robotika STEM & Eksperimen Sains',
      catatan_bakat: 'Memiliki rasa ingin tahu tinggi dalam rakitan elektronik sederhana dan matematika logika.',
      tahun_masuk: 2024,
    },
    {
      id: 7,
      nama: 'Siti Aminah',
      username: 'murid_siti',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456790',
      kelas: 'Kelas 4B',
      jenis_kelamin: 'P',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2015-08-20',
      alamat: 'Jl. Veteran Gg. 3 No. 12, Gresik',
      nama_ortu: 'Ibu Fatimah Zahra',
      wa_ortu: '085732112234',
      minat_utama: 'Seni Tari Pesisir Gresik & Melukis',
      catatan_bakat: 'Keluwesan gerak tari sangat baik, pernah tampil di pentas seni tingkat kecamatan.',
      tahun_masuk: 2024,
    },
    {
      id: 8,
      nama: 'Rizky Maulana',
      username: 'murid_rizky',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456791',
      kelas: 'Kelas 5B',
      jenis_kelamin: 'L',
      tempat_lahir: 'Surabaya',
      tanggal_lahir: '2014-11-03',
      alamat: 'Perumahan Gresik Kota Baru (GKB) Blok C-14',
      nama_ortu: 'Bpk. Bambang Irawan',
      wa_ortu: '085732112235',
      minat_utama: 'Olahraga Catur Taktis & Atletik Lari',
      catatan_bakat: 'Konsentrasi tinggi dan memiliki pemahaman kalkulasi langkah catur menengah.',
      tahun_masuk: 2024,
    },
    {
      id: 9,
      nama: 'Zahra Putri',
      username: 'murid_zahra',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456792',
      kelas: 'Kelas 4A',
      jenis_kelamin: 'P',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2015-02-14',
      alamat: 'Jl. Pahlawan No. 78, Gresik',
      nama_ortu: 'Ibu Ratna Dewi',
      wa_ortu: '085732112236',
      minat_utama: 'Tilawatil Qur\'an & Vokal Hadrah',
      catatan_bakat: 'Makhraj huruf fasih dan artikulasi vokal merdu dengan tajwid baik.',
      tahun_masuk: 2025,
    },
    {
      id: 13,
      nama: 'Muhammad Farhan',
      username: 'murid_farhan',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456793',
      kelas: 'Kelas 6A',
      jenis_kelamin: 'L',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2013-09-17',
      alamat: 'Jl. Dr. Soetomo No. 22, Gresik',
      nama_ortu: 'Bpk. Hendra Wijaya',
      wa_ortu: '085732112237',
      minat_utama: 'Olimpiade Matematika & Sains',
      catatan_bakat: 'Unggul dalam penyelesaian soal cerita non-rutin dan logika analitis.',
      tahun_masuk: 2024,
    },
    {
      id: 14,
      nama: 'Aisyah Nur Salsabila',
      username: 'murid_aisyah',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456794',
      kelas: 'Kelas 3B',
      jenis_kelamin: 'P',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2016-05-25',
      alamat: 'Jl. Usman Sadar No. 89, Gresik',
      nama_ortu: 'Ibu Diana Safitri',
      wa_ortu: '085732112238',
      minat_utama: 'Pramuka Penggalang & Menyanyi',
      catatan_bakat: 'Disiplin tinggi, ceria, dan aktif dalam kepanduan siaga mula.',
      tahun_masuk: 2025,
    },
    {
      id: 15,
      nama: 'Dimas Aditya',
      username: 'murid_dimas',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456795',
      kelas: 'Kelas 4B',
      jenis_kelamin: 'L',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2015-06-11',
      alamat: 'Jl. Jaksa Agung Suprapto No. 34, Gresik',
      nama_ortu: 'Bpk. Eko Wahyudi',
      wa_ortu: '085732112239',
      minat_utama: 'Olimpiade Matematika & Sains (OSN)',
      catatan_bakat: 'Tertarik pada eksperimen fisika gravitasi dan pemecahan teka-teki bangun ruang.',
      tahun_masuk: 2025,
    },
    {
      id: 16,
      nama: 'Nabila Azzahra',
      username: 'murid_nabila',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456796',
      kelas: 'Kelas 3A',
      jenis_kelamin: 'P',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2016-01-19',
      alamat: 'Jl. KH. Kholil No. 56, Kebomas, Gresik',
      nama_ortu: 'Ibu Maryam Ulfa',
      wa_ortu: '085732112240',
      minat_utama: 'Kriya Seni Rupa & Melukis',
      catatan_bakat: 'Kerapian sketsa gambar dan penguasaan gradasi warna cat air sangat menonjol.',
      tahun_masuk: 2025,
    },
    {
      id: 17,
      nama: 'Kenzo Daniswara',
      username: 'murid_kenzo',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456797',
      kelas: 'Kelas 1A',
      jenis_kelamin: 'L',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2018-03-08',
      alamat: 'Perumahan Bukit Mas Indah Blok D-08, Driyorejo, Gresik',
      nama_ortu: 'Bpk. Dani Setiawan',
      wa_ortu: '085732112241',
      minat_utama: 'Robotika STEM & Eksperimen Sains',
      catatan_bakat: 'Suka menyusun balok lego rumit dan memiliki konsentrasi visual-spasial sangat baik.',
      tahun_masuk: 2026,
    },
    {
      id: 18,
      nama: 'Kayla Althafunisa',
      username: 'murid_kayla',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456798',
      kelas: 'Kelas 1B',
      jenis_kelamin: 'P',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2018-07-22',
      alamat: 'Jl. Sunan Giri Gg. 5 No. 17, Gresik',
      nama_ortu: 'Ibu Annisa Pratiwi',
      wa_ortu: '085732112242',
      minat_utama: 'Seni Tari Tradisional Pesisir',
      catatan_bakat: 'Peka terhadap irama musik rebana dan sangat antusias mengikuti gerak tari dasar.',
      tahun_masuk: 2026,
    },
    {
      id: 19,
      nama: 'Rayyan Al-Ghifari',
      username: 'murid_rayyan',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456799',
      kelas: 'Kelas 2A',
      jenis_kelamin: 'L',
      tempat_lahir: 'Surabaya',
      tanggal_lahir: '2017-09-14',
      alamat: 'Jl. Brotonegoro No. 88, Manyar, Gresik',
      nama_ortu: 'Bpk. Fikri Al-Ghifari',
      wa_ortu: '085732112243',
      minat_utama: 'Olahraga Catur Taktis & Logika',
      catatan_bakat: 'Mampu mengingat posisi bidak catur dan senang memecahkan teka-teki logika 2 langkah skakmat.',
      tahun_masuk: 2026,
    },
    {
      id: 20,
      nama: 'Safira Maulida',
      username: 'murid_safira',
      password_hash: 'password123',
      role: 'murid',
      nip_nisn: '0123456800',
      kelas: 'Kelas 2B',
      jenis_kelamin: 'P',
      tempat_lahir: 'Gresik',
      tanggal_lahir: '2017-12-05',
      alamat: 'Jl. RE Martadinata No. 102, Gresik',
      nama_ortu: 'Ibu Siti Nurhaliza',
      wa_ortu: '085732112244',
      minat_utama: 'Tilawatil Qur\'an & Vokal Hadrah',
      catatan_bakat: 'Suara merdu natural, pelafalan tajwid lancar pada surat-surat juz 30.',
      tahun_masuk: 2026,
    },
    {
      id: 10,
      nama: 'Bpk. Agus Pratama (Wali Budi)',
      username: 'ortu_budi',
      password_hash: 'password123',
      role: 'orang_tua',
      anak_id: 6,
      nomor_wa: '085732112233',
    },
    {
      id: 11,
      nama: 'Ibu Fatimah Zahra (Wali Siti)',
      username: 'ortu_siti',
      password_hash: 'password123',
      role: 'orang_tua',
      anak_id: 7,
      nomor_wa: '085732112234',
    },
    {
      id: 12,
      nama: 'Bpk. Bambang Irawan (Wali Rizky)',
      username: 'ortu_rizky',
      password_hash: 'password123',
      role: 'orang_tua',
      anak_id: 8,
      nomor_wa: '085732112235',
    },
  ];

  teacherAssets: TeacherAsset[] = [
    {
      id: 1,
      user_id: 2,
      latar_belakang_pendidikan: 'S1 Pendidikan Fisika & Sains, Universitas Negeri Surabaya (UNESA)',
      keahlian_khusus: 'Olimpiade Sains IPA, Eksperimen Fisika Sederhana & Robotika STEM Lego Dasar',
      catatan_konfirmasi_ks: 'Memiliki portofolio bimbingan olimpiade sains yang sangat mumpuni. Ditetapkan sebagai Pembina Utama Klub Sains & Inovasi Cilik UPT SDN 275 Gresik.',
      status_konfirmasi: true,
      nama_guru: 'Nur Aini, S.Pd',
      nip: '198503142010012021',
      komitmen_empati: 'Siap mendampingi murid dengan kesabaran tinggi, menggunakan pendekatan penemuan konsep langsung (hands-on experiment) agar anak tidak takut sains.',
      rekomendasi_ekstra: 'Klub Sains & Inovasi Cilik',
      bidang_sertifikasi: 'Sertifikasi Pendidik Profesional Sains SD & Pelatih Pembina OSN IPA LPMP Jatim',
      updated_at: '2026-09-10',
    },
    {
      id: 2,
      user_id: 3,
      latar_belakang_pendidikan: 'S1 Pendidikan Seni Tari & Musik (Sendratasik), Universitas Negeri Surabaya',
      keahlian_khusus: 'Koreografi Tari Tradisional Pesisir Gresik (Tari Damar Kurung), Musik Rebana Samrah & Karawitan',
      catatan_konfirmasi_ks: 'Aset kultural berharga sekolah. Mampu melatih koreografi tanpa perlu sewa sanggar luar sehingga mengefisienkan anggaran BOS sekolah secara signifikan.',
      status_konfirmasi: true,
      nama_guru: 'Joko Santoso, S.Pd',
      nip: '198708212011011009',
      komitmen_empati: 'Membangun kedisiplinan dan kecintaan anak terhadap warisan leluhur Gresik dengan suasana latihan yang menggembirakan.',
      rekomendasi_ekstra: 'Seni Tari Tradisional "Damar Kurung"',
      bidang_sertifikasi: 'Pelatih Tari Tradisional Dewan Kesenian Gresik',
      updated_at: '2026-09-11',
    },
    {
      id: 3,
      user_id: 4,
      latar_belakang_pendidikan: 'S1 Pendidikan Guru Sekolah Dasar (PGSD), Universitas Negeri Malang',
      keahlian_khusus: 'Kriya Daur Ulang Ramah Lingkungan, Seni Batik Ecoprint Daun Jarak, dan Kepramukaan Golongan Siaga/Penggalang',
      catatan_konfirmasi_ks: 'Sangat terampil dan telaten. Ditugaskan mengasuh ekstrakurikuler Kriya Seni & Prakarya Terapan untuk persiapan FLS2N tingkat kecamatan & kabupaten.',
      status_konfirmasi: true,
      nama_guru: 'Siti Rahayu, S.Pd',
      nip: '199011052015022004',
      komitmen_empati: 'Mengasah kepekaan estetika dan kecermatan motorik halus anak melalui bahan-bahan alami di sekitar pekarangan sekolah.',
      rekomendasi_ekstra: 'Kriya Seni & Batik Ecoprint',
      bidang_sertifikasi: 'Ijazah Pembina Pramuka KMD & Sertifikat Pelatihan Kerajinan Tangan Jatim',
      updated_at: '2026-09-12',
    },
    {
      id: 4,
      user_id: 5,
      latar_belakang_pendidikan: 'S1 Pendidikan Agama Islam (PAI), UIN Sunan Ampel Surabaya',
      keahlian_khusus: 'Seni Khat Kaligrafi Arab (Naskhi & Riqah), Tilawatil Quran, serta Taktik Catur Cepat',
      catatan_konfirmasi_ks: 'Proses wawancara 1-on-1 disetujui. Disiapkan untuk pembinaan ekstrakurikuler Kaligrafi & Tilawah serta persiapan kejuaraan Pentas PAI.',
      status_konfirmasi: true,
      nama_guru: 'Ahmad Zaki, S.Pd.I',
      nip: '199304102019031008',
      komitmen_empati: 'Menumbuhkan ketenangan jiwa, adab santun, dan ketajaman konsentrasi anak melalui seni menulis kalam ilahi.',
      rekomendasi_ekstra: 'Kaligrafi & Seni Tilawah Al-Quran',
      bidang_sertifikasi: 'Sertifikat Kaligrafer Lemka & Pembina Tartil LPTQ',
      updated_at: '2026-09-14',
    },
  ];

  extracurriculars: Extracurricular[] = [
    {
      id: 1,
      nama_ekstra: 'Klub Sains & Inovasi Cilik',
      pembina_id: 2,
      kategori: 'akademik',
      deskripsi: 'Wadah eksplorasi sains interaktif, eksperimen fisika sederhana, persiapan Olimpiade Sains Nasional (OSN) IPA, dan pengenalan mekanika robotika ramah anak.',
      pembina_nama: 'Nur Aini, S.Pd',
      jadwal: 'Selasa & Kamis, 14.30 - 16.00 WIB',
      ruang: 'Laboratorium IPA & Komputer SDN 275 Gresik',
      biaya_efisiensi: 3000000,
      kuota: 25,
      jumlah_peserta: 18,
    },
    {
      id: 2,
      nama_ekstra: 'Seni Tari Tradisional "Damar Kurung"',
      pembina_id: 3,
      kategori: 'non_akademik',
      deskripsi: 'Pelatihan gerak tari tradisional khas Pesisir Gresik dan Jawa Timur, melatih kelenturan tubuh, apresiasi musik gamelan samrah, dan persiapan FLS2N Seni Tari.',
      pembina_nama: 'Joko Santoso, S.Pd',
      jadwal: 'Rabu & Sabtu, 14.00 - 15.30 WIB',
      ruang: 'Aula Terbuka Sasana Wiyata',
      biaya_efisiensi: 2500000,
      kuota: 30,
      jumlah_peserta: 22,
    },
    {
      id: 3,
      nama_ekstra: 'Kriya Seni & Batik Ecoprint',
      pembina_id: 4,
      kategori: 'non_akademik',
      deskripsi: 'Pengembangan talenta visual dan keterampilan membuat kriya anyaman daun kelapa/pandan serta teknik cetak motif alami batik ecoprint ramah lingkungan.',
      pembina_nama: 'Siti Rahayu, S.Pd',
      jadwal: 'Jumat, 13.30 - 15.00 WIB',
      ruang: 'Ruang Prakarya & Lingkungan Hidup',
      biaya_efisiensi: 2000000,
      kuota: 20,
      jumlah_peserta: 15,
    },
    {
      id: 4,
      nama_ekstra: 'Kaligrafi & Seni Tilawah Al-Quran',
      pembina_id: 5,
      kategori: 'non_akademik',
      deskripsi: 'Pelatihan menulis indah huruf hijaiyah berkaidah naskhi, mengasah kesabaran, dan memadukan lantunan tilawah tartil merdu untuk ajang Pentas PAI.',
      pembina_nama: 'Ahmad Zaki, S.Pd.I',
      jadwal: 'Senin & Kamis, 15.00 - 16.30 WIB',
      ruang: 'Musholla Raudhatul Ilmi SDN 275 Gresik',
      biaya_efisiensi: 1800000,
      kuota: 25,
      jumlah_peserta: 16,
    },
    {
      id: 5,
      nama_ekstra: 'Klub Matematika & Logika Nalaria',
      pembina_id: 2,
      kategori: 'akademik',
      deskripsi: 'Pendalaman penalaran matematika realistik (PMR), problem solving olimpiade dasar, dan permainan logika catur taktis untuk melatih nalar kritis.',
      pembina_nama: 'Nur Aini, S.Pd',
      jadwal: 'Rabu, 14.30 - 16.00 WIB',
      ruang: 'Kelas 5A',
      biaya_efisiensi: 2200000,
      kuota: 20,
      jumlah_peserta: 12,
    },
  ];

  studentInterests: StudentInterest[] = [
    {
      id: 1,
      murid_id: 6,
      ekstra_id: 1,
      persetujuan_ortu: true,
      tanggal_daftar: '2026-09-01',
      murid_nama: 'Budi Pratama',
      kelas: 'Kelas 5A',
      ekstra_nama: 'Klub Sains & Inovasi Cilik',
      kategori_ekstra: 'akademik',
      pembina_nama: 'Nur Aini, S.Pd',
      catatan_ortu: 'Sangat mendukung, Budi memiliki minat besar di bidang eksperimen dan sains.',
      tanggal_persetujuan: '2026-09-02',
    },
    {
      id: 2,
      murid_id: 7,
      ekstra_id: 2,
      persetujuan_ortu: true,
      tanggal_daftar: '2026-09-02',
      murid_nama: 'Siti Aminah',
      kelas: 'Kelas 4B',
      ekstra_nama: 'Seni Tari Tradisional "Damar Kurung"',
      kategori_ekstra: 'non_akademik',
      pembina_nama: 'Joko Santoso, S.Pd',
      catatan_ortu: 'Ananda ingin melestarikan tarian khas Gresik, kami setuju sepenuhnya.',
      tanggal_persetujuan: '2026-09-03',
    },
    {
      id: 3,
      murid_id: 8,
      ekstra_id: 1,
      persetujuan_ortu: false,
      tanggal_daftar: '2026-09-05',
      murid_nama: 'Rizky Maulana',
      kelas: 'Kelas 5B',
      ekstra_nama: 'Klub Sains & Inovasi Cilik',
      kategori_ekstra: 'akademik',
      pembina_nama: 'Nur Aini, S.Pd',
      catatan_ortu: 'Menunggu konfirmasi jadwal les mengaji sore di rumah.',
    },
    {
      id: 4,
      murid_id: 9,
      ekstra_id: 3,
      persetujuan_ortu: true,
      tanggal_daftar: '2026-09-03',
      murid_nama: 'Zahra Putri',
      kelas: 'Kelas 4A',
      ekstra_nama: 'Kriya Seni & Batik Ecoprint',
      kategori_ekstra: 'non_akademik',
      pembina_nama: 'Siti Rahayu, S.Pd',
      catatan_ortu: 'Disetujui. Semoga Zahra bisa mengembangkan hobi seninya.',
      tanggal_persetujuan: '2026-09-04',
    },
    {
      id: 5,
      murid_id: 6,
      ekstra_id: 4,
      persetujuan_ortu: true,
      tanggal_daftar: '2026-09-04',
      murid_nama: 'Budi Pratama',
      kelas: 'Kelas 5A',
      ekstra_nama: 'Kaligrafi & Seni Tilawah Al-Quran',
      kategori_ekstra: 'non_akademik',
      pembina_nama: 'Ahmad Zaki, S.Pd.I',
      catatan_ortu: 'Bagus untuk melatih ketenangan dan memperhalus tulisan.',
      tanggal_persetujuan: '2026-09-05',
    },
    {
      id: 6,
      murid_id: 15,
      ekstra_id: 1,
      persetujuan_ortu: true,
      tanggal_daftar: '2025-08-10',
      murid_nama: 'Dimas Aditya',
      kelas: 'Kelas 4B',
      ekstra_nama: 'Klub Sains & Inovasi Cilik',
      kategori_ekstra: 'akademik',
      pembina_nama: 'Nur Aini, S.Pd',
      catatan_ortu: 'Dimas sangat gemar sains, mohon bimbingan intensif.',
      tanggal_persetujuan: '2025-08-12',
    },
    {
      id: 7,
      murid_id: 16,
      ekstra_id: 3,
      persetujuan_ortu: true,
      tanggal_daftar: '2025-08-15',
      murid_nama: 'Nabila Azzahra',
      kelas: 'Kelas 3A',
      ekstra_nama: 'Kriya Seni & Batik Ecoprint',
      kategori_ekstra: 'non_akademik',
      pembina_nama: 'Siti Rahayu, S.Pd',
      catatan_ortu: 'Nabila sangat bersemangat melukis dan membuat prakarya.',
      tanggal_persetujuan: '2025-08-16',
    },
    {
      id: 8,
      murid_id: 17,
      ekstra_id: 1,
      persetujuan_ortu: true,
      tanggal_daftar: '2026-07-20',
      murid_nama: 'Kenzo Daniswara',
      kelas: 'Kelas 1A',
      ekstra_nama: 'Klub Sains & Inovasi Cilik',
      kategori_ekstra: 'akademik',
      pembina_nama: 'Nur Aini, S.Pd',
      catatan_ortu: 'Dukungan penuh untuk eksplorasi robotika usia dini.',
      tanggal_persetujuan: '2026-07-22',
    },
    {
      id: 9,
      murid_id: 18,
      ekstra_id: 2,
      persetujuan_ortu: true,
      tanggal_daftar: '2026-07-25',
      murid_nama: 'Kayla Althafunisa',
      kelas: 'Kelas 1B',
      ekstra_nama: 'Seni Tari Tradisional "Damar Kurung"',
      kategori_ekstra: 'non_akademik',
      pembina_nama: 'Joko Santoso, S.Pd',
      catatan_ortu: 'Senang sekali anak saya bisa belajar tari khas Gresik.',
      tanggal_persetujuan: '2026-07-27',
    },
  ];

  mentoringLogs: MentoringLog[] = [
    {
      id: 1,
      ekstra_id: 1,
      pembina_id: 2,
      murid_id: 6,
      tanggal: '2026-09-15',
      moda_pembelajaran: 'memahami',
      catatan_kegiatan: 'Moda Memahami: Mengupas tuntas hukum Archimedes dan fenomena massa jenis zat cair. Murid diajak mengamati mengapa telur mengapung di air garam pekat namun tenggelam di air murni.',
      catatan_supervisi_ks: 'Luar biasa. Penanaman konsep dasar sudah sangat tepat sasaran. Berikan pemantik pertanyaan kritis untuk sesi aplikasi berikutnya.',
      ekstra_nama: 'Klub Sains & Inovasi Cilik',
      pembina_nama: 'Nur Aini, S.Pd',
      murid_nama: 'Budi Pratama',
      indikator_capaian: 'Murid mampu mengidentifikasi pengaruh densitas cairan terhadap gaya apung benda padat.',
      status_supervisi: true,
    },
    {
      id: 2,
      ekstra_id: 1,
      pembina_id: 2,
      murid_id: 6,
      tanggal: '2026-09-18',
      moda_pembelajaran: 'mengaplikasi',
      catatan_kegiatan: 'Moda Mengaplikasi: Murid mempraktikkan perancangan miniatur kapal penyelamat beban menggunakan botol sisa dan koin penyeimbang. Mengukur kapasitas muatan apung stabil.',
      catatan_supervisi_ks: 'Pendekatan pembelajaran mendalam (Deep Learning) nyata terlaksana. Murid aktif berkarya dan menguji hipotesis langsung.',
      ekstra_nama: 'Klub Sains & Inovasi Cilik',
      pembina_nama: 'Nur Aini, S.Pd',
      murid_nama: 'Budi Pratama',
      indikator_capaian: 'Murid berhasil merancang dan menguji daya muat kapal model tanpa terbalik.',
      status_supervisi: true,
    },
    {
      id: 3,
      ekstra_id: 2,
      pembina_id: 3,
      murid_id: 7,
      tanggal: '2026-09-16',
      moda_pembelajaran: 'mengaplikasi',
      catatan_kegiatan: 'Moda Mengaplikasi: Melatih sinkronisasi gerakan tangan "Ukel Trap Jamang" dengan ritme ketukan kendang kendang samrah Gresik tempo 4/4.',
      catatan_supervisi_ks: 'Gerakan anak-anak terlihat semakin luwes. Perhatikan kenyamanan busana latihan agar stamina tetap terjaga.',
      ekstra_nama: 'Seni Tari Tradisional "Damar Kurung"',
      pembina_nama: 'Joko Santoso, S.Pd',
      murid_nama: 'Siti Aminah',
      indikator_capaian: 'Keluwesan gerak tangan dan ketepatan tempo ketukan gamelan samrah.',
      status_supervisi: true,
    },
    {
      id: 4,
      ekstra_id: 3,
      pembina_id: 4,
      murid_id: 9,
      tanggal: '2026-09-17',
      moda_pembelajaran: 'merefleksi',
      catatan_kegiatan: 'Moda Merefleksi: Setelah proses steaming kain ecoprint selesai, murid mengevaluasi bersama mengapa daun jati muda mengeluarkan pigmen lebih kontras dibanding daun mangga, serta menuliskan catatan perbaikan perlakuan mordan tawas.',
      catatan_supervisi_ks: 'Refleksi mendalam yang membangun pola pikir tumbuh (growth mindset). Murid belajar dari kekurangan hasil karya pertamanya.',
      ekstra_nama: 'Kriya Seni & Batik Ecoprint',
      pembina_nama: 'Siti Rahayu, S.Pd',
      murid_nama: 'Zahra Putri',
      indikator_capaian: 'Kemampuan bernalar kritis mengevaluasi faktor keberhasilan transfer tanin pada kain alami.',
      status_supervisi: true,
    },
    {
      id: 5,
      ekstra_id: 4,
      pembina_id: 5,
      murid_id: 6,
      tanggal: '2026-09-19',
      moda_pembelajaran: 'memahami',
      catatan_kegiatan: 'Moda Memahami: Mengenal anatomi pena bambu (kalam) serta sudut kemiringan goresan 70 derajat pada pembuatan huruf Alif dan Lam gaya Naskhi.',
      catatan_supervisi_ks: '',
      ekstra_nama: 'Kaligrafi & Seni Tilawah Al-Quran',
      pembina_nama: 'Ahmad Zaki, S.Pd.I',
      murid_nama: 'Budi Pratama',
      indikator_capaian: 'Pengenalan kaidah dasar ketebalan goresan pena kaligrafi tradisional.',
      status_supervisi: false,
    },
  ];

  achievements: Achievement[] = [
    {
      id: 1,
      ekstra_id: 1,
      murid_id: 6,
      nama_lomba: 'Lomba Cipta Alat Peraga Sains & Kategori Rekayasa Siswa SD',
      tingkat: 'kecamatan',
      capaian: 'Juara 1',
      tanggal_kegiatan: '2026-08-25',
      ekstra_nama: 'Klub Sains & Inovasi Cilik',
      murid_nama: 'Budi Pratama',
      kelas: 'Kelas 5A',
      penyelenggara: 'Kelompok Kerja Guru (KKG) IPA Kec. Menganti Gresik',
      keterangan: 'Mempresentasikan model filtrasi air sederhana berbahan sabut kelapa dan arang aktif.',
    },
    {
      id: 2,
      ekstra_id: 2,
      murid_id: 7,
      nama_lomba: 'Festival Lomba Seni Siswa Nasional (FLS2N) Cabang Tari Kreasi Tradisional',
      tingkat: 'kabupaten',
      capaian: 'Juara 2',
      tanggal_kegiatan: '2026-09-08',
      ekstra_nama: 'Seni Tari Tradisional "Damar Kurung"',
      murid_nama: 'Siti Aminah',
      kelas: 'Kelas 4B',
      penyelenggara: 'Dinas Pendidikan Kabupaten Gresik',
      keterangan: 'Membawakan tari kreasi Damar Kurung Pesisir dengan apresiasi tinggi dewan juri.',
    },
    {
      id: 3,
      ekstra_id: 3,
      murid_id: 9,
      nama_lomba: 'Gelar Kreativitas Pelajar & Kriya Anyam Ramah Lingkungan',
      tingkat: 'kecamatan',
      capaian: 'Juara 1',
      tanggal_kegiatan: '2026-08-30',
      ekstra_nama: 'Kriya Seni & Batik Ecoprint',
      murid_nama: 'Zahra Putri',
      kelas: 'Kelas 4A',
      penyelenggara: 'Kwartir Ranting Gerakan Pramuka Kecamatan',
      keterangan: 'Karya keranjang serbaguna anyaman limbah pelepah pisang dipadu ecoprint.',
    },
    {
      id: 4,
      ekstra_id: 1,
      murid_id: 6,
      nama_lomba: 'Olimpiade Sains Terbuka Matematika & IPA Tingkat SD/MI',
      tingkat: 'kabupaten',
      capaian: 'Juara Harapan 1',
      tanggal_kegiatan: '2026-09-02',
      ekstra_nama: 'Klub Sains & Inovasi Cilik',
      murid_nama: 'Budi Pratama',
      kelas: 'Kelas 5A',
      penyelenggara: 'Forum Musyawarah Guru Sains Gresik',
      keterangan: 'Meraih skor 88.5 pada babak final eksperimen laboratorium sains terpadu.',
    },
    {
      id: 5,
      ekstra_id: 4,
      murid_id: 8,
      nama_lomba: 'Musabaqah Khattil Quran (MKQ) Hari Santri Nasional',
      tingkat: 'sekolah',
      capaian: 'Juara 1',
      tanggal_kegiatan: '2026-08-20',
      ekstra_nama: 'Kaligrafi & Seni Tilawah Al-Quran',
      murid_nama: 'Rizky Maulana',
      kelas: 'Kelas 5B',
      penyelenggara: 'Panitia PHBI UPT SDN 275 Gresik',
      keterangan: 'Karya naskhi terindah dengan ornamen khas Damar Kurung.',
    },
  ];

  evaluationsFeedback: EvaluationFeedback[] = [
    {
      id: 1,
      user_id: 6,
      peran: 'murid',
      isi_umpan_balik: 'Saya sangat senang bisa ikut Klub Sains. Bu Nur Aini mengajar dengan cara yang mudah dimengerti, banyak praktik eksperimen langsung dan tidak bikin bosan!',
      created_at: '2026-09-18 16:30',
      user_nama: 'Budi Pratama (Murid)',
      rating: 5,
      aspek_evaluasi: 'Metode Pembelajaran & Praktik Langsung',
    },
    {
      id: 2,
      user_id: 10,
      peran: 'orang_tua',
      isi_umpan_balik: 'Program SI-PASTI ini sangat luar biasa. Kami sebagai orang tua tidak perlu lagi keluar biaya jutaan untuk les privat luar, karena potensi guru-guru SDN 275 Gresik sendiri ternyata sangat hebat dan tulus membimbing.',
      created_at: '2026-09-18 19:15',
      user_nama: 'Bpk. Agus Pratama (Wali Budi)',
      rating: 5,
      aspek_evaluasi: 'Efisiensi Anggaran & Kualitas Guru',
    },
    {
      id: 3,
      user_id: 2,
      peran: 'guru',
      isi_umpan_balik: 'Dengan adanya pemetaan aset internal ini, saya merasa keahlian sains saya benar-benar dihargai dan dimanfaatkan optimal oleh sekolah. Dukungan kepala sekolah saat supervisi juga sangat memberi motivasi.',
      created_at: '2026-09-19 11:00',
      user_nama: 'Nur Aini, S.Pd (Guru)',
      rating: 5,
      aspek_evaluasi: 'Apresiasi & Iklim Kolaboratif Sekolah',
    },
    {
      id: 4,
      user_id: 11,
      peran: 'orang_tua',
      isi_umpan_balik: 'Putri kami Siti Aminah jadi makin berani tampil di depan umum setelah dibina Pak Joko di sanggar tari sekolah. Laporan perkembangan anak juga terpantau jelas di aplikasi ini.',
      created_at: '2026-09-19 15:40',
      user_nama: 'Ibu Fatimah Zahra (Wali Siti)',
      rating: 5,
      aspek_evaluasi: 'Transparansi & Dampak Positif Anak',
    },
    {
      id: 5,
      user_id: 7,
      peran: 'murid',
      isi_umpan_balik: 'Tari Damar Kurung seru sekali gerakannya, Pak Joko sabar banget melatih sampai kami kompak semua.',
      created_at: '2026-09-19 16:10',
      user_nama: 'Siti Aminah (Murid)',
      rating: 5,
      aspek_evaluasi: 'Keseruan & Kesabaran Pembina',
    },
  ];

  // Helper methods
  findUserByUsername(username: string): User | undefined {
    return this.users.find((u) => u.username.toLowerCase() === username.toLowerCase());
  }

  findUserById(id: number): User | undefined {
    return this.users.find((u) => u.id === id);
  }

  getAchievementStats(): AchievementStats {
    const stats: AchievementStats = {
      total_prestasi: this.achievements.length,
      tingkat_kabupaten: this.achievements.filter((a) => a.tingkat === 'kabupaten').length,
      tingkat_kecamatan: this.achievements.filter((a) => a.tingkat === 'kecamatan').length,
      tingkat_sekolah: this.achievements.filter((a) => a.tingkat === 'sekolah').length,
      prestasi_per_ekstra: {},
      prestasi_terbaru: [...this.achievements].sort(
        (a, b) => new Date(b.tanggal_kegiatan).getTime() - new Date(a.tanggal_kegiatan).getTime()
      ),
    };

    for (const a of this.achievements) {
      const name = a.ekstra_nama || 'Lainnya';
      stats.prestasi_per_ekstra[name] = (stats.prestasi_per_ekstra[name] || 0) + 1;
    }

    return stats;
  }

  getFeedbackSummary(): FeedbackSummary {
    const total = this.evaluationsFeedback.length;
    const totalRating = this.evaluationsFeedback.reduce((sum, f) => sum + (f.rating || 5), 0);
    const avg = total > 0 ? Number((totalRating / total).toFixed(1)) : 5.0;

    const summary: FeedbackSummary = {
      total_responden: total,
      rerata_kepuasan: avg,
      distribusi_peran: {
        murid: this.evaluationsFeedback.filter((f) => f.peran === 'murid').length,
        orang_tua: this.evaluationsFeedback.filter((f) => f.peran === 'orang_tua').length,
        guru: this.evaluationsFeedback.filter((f) => f.peran === 'guru').length,
      },
      aspek_tertinggi: 'Efisiensi Anggaran & Kualitas Guru Internal',
      daftar_masukan: [...this.evaluationsFeedback].sort(
        (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
      ),
    };

    return summary;
  }
}

export const db = new DataStore();
